package hw1;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Caelan
 */
public class JFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame3
     */
    public JFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jToggleButton1.setText("Spin!");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel4.setText("Insert an amount to play.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Amount Won: $0.00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Amount Won This Spin: $");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Amount Inserted: $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(215, 215, 215))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(239, 239, 239))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
 // TODO add your handling code here:
 
        if(jToggleButton1.isSelected()) {
        Random rd = new Random();
        int random = rd.nextInt(6)+1;
        switch(random){
            case 1:
               
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Apple.jpg")));

                break;
            case 2:
                
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Banana.jpg")));

                break;
            case 3:
                
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Cherries.jpg")));

                break;
            case 4:
                
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Grapes.jpg")));

                break;
            case 5:
               
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Lemon.jpg")));

                break;
            case 6:
               
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Lime.jpg")));

                break;
            case 7:
                
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Orange.jpg")));

                break;
            case 8:
                
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Pear.jpg")));

                break;
            case 9:
                
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Strawberry.jpg")));

                break;
            case 10:
               
                jLabel1.setIcon(new ImageIcon(getClass().getResource("images/Watermelon.jpg")));

                break;
           
        }
        Random rd2=new Random();
        int random2 = rd2.nextInt(6)+1;
        switch(random2){
           case 1:
               
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Apple.jpg")));

                break;
            case 2:
                
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Banana.jpg")));

                break;
            case 3:
                
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Cherries.jpg")));

                break;
            case 4:
                
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Grapes.jpg")));

                break;
            case 5:
               
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Lemon.jpg")));

                break;
            case 6:
               
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Lime.jpg")));

                break;
            case 7:
                
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Orange.jpg")));

                break;
            case 8:
                
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Pear.jpg")));

                break;
            case 9:
                
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Strawberry.jpg")));

                break;
            case 10:
               
                jLabel2.setIcon(new ImageIcon(getClass().getResource("images/Watermelon.jpg")));

                break;
           
        }
        Random rd3  =new Random();
        int random3 = rd3.nextInt(6)+1;
        switch(random3){
           case 1:
               
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Apple.jpg")));

                break;
            case 2:
                
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Banana.jpg")));

                break;
            case 3:
                
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Cherries.jpg")));

                break;
            case 4:
                
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Grapes.jpg")));

                break;
            case 5:
               
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Lemon.jpg")));

                break;
            case 6:
               
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Lime.jpg")));

                break;
            case 7:
                
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Orange.jpg")));

                break;
            case 8:
                
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Pear.jpg")));

                break;
            case 9:
                
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Strawberry.jpg")));

                break;
            case 10:
               
                jLabel3.setIcon(new ImageIcon(getClass().getResource("images/Watermelon.jpg")));

                break;
             
             }
        
        if(random == random2 || random == random3 || random2 == random || random2 == random3 || random3 == random || random3 == random2){
            
            String getBet = jTextField1.getText();
            double betAmount = Double.parseDouble(getBet);
            
            betAmount = betAmount + betAmount;
            
            String getTotal = jLabel5.getText();
            
            String s1=getTotal;    
            String substr = s1.substring(19); // Starts with 19 and goes to end  
            double subDub = Double.parseDouble(substr);
            
            subDub = subDub + betAmount;
            
             jLabel4.setText("Sweet! DOUBLE WIN X2!!!");
             jLabel6.setText("Amount Won This Spin: $"+betAmount); 
             jLabel5.setText("Total Amount Won: $"+subDub);
            
        }
         else {
            
        }
        
        if(random != random2 && random != random3 && random2 != random && random2 != random3 && random3 != random && random3 != random2){
            
            String getTotal = jLabel5.getText();
            
             jLabel4.setText("No Luck. Play Again!");
             jLabel6.setText("Amount Won This Spin: $0.00"); 
             jLabel5.setText(getTotal);
            
        }
         else {
            
        }
        
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
